# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8b11ddcb0f7de6b2ca42db4b6dfb1ac6d9bf45f71554e2262d4977b37b04bf1b60abe52b269e721beaf7f3c2e591deb06b6ade2d138a29933dbe075d57d71c

test:
  secret_key_base: 04992627f6ba3e03c1ea4a9c74dd65e17d86bac84d498acdea16bd2cccd087c3939ce3b3914b568bfbf98b967101745954343f15a0e7ea6ca949d9718df22217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
